#this is the yaml file for nusim basic_world configuration
---
robot_start: [-0.6,0.8,1.57]
cylinder_radius: 0.3
cylinders_start_x: [-0.6,0.6,0.6]
cylinders_start_y: [-0.8,-0.8,0.8]
#the length of the walls
x_length: 2
y_length: 2
#nusim_config(for debug only)
x0: -0.6
y0: -0.8
theta0: 0
rate: 50
wheel_mean: 0
wheel_stddev: 0.5
slip_min: 0
slip_max: 1
#basic_sensor_config
basic_sensor_variance: 0.01
#max_range in radians
max_range: 2